# update this variables
@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiNjgwM2M5MzQtMTdkYy00Yzk0LTljMDMtMmZjMjRlZjBiYTU2IiwibmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAdGVzdCIsImFkbWluIjp0cnVlfSwiZXhwIjoxNzI5NTA1OTUzfQ.GnE8jlS_sRIO1i9hj_XyzMhkFhvRfJ2klIYzFvcoBU8
@id = 6803c934-17dc-4c94-9c03-2fc24ef0ba56

### create user
POST http://localhost:3000/user
Content-Type: application/json

{
  "name" : "test",
  "email" : "test@email.com",
  "password" : "test"
}

### login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email" : "test@test",
  "password" : "test"
}

### update user
PUT http://localhost:3000/user/{{id}}
Content-Type: application/json
Authorization: {{authToken}}

{
  "name" : "test updated",
  "password" : "test updated"
}