# update this variables
@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiNDliY2JmNDYtYWRhZC00NDgzLWI2Y2ItYzg5NzgzNGRmMWRmIiwibmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAdGVzdCIsImFkbWluIjpmYWxzZX0sImV4cCI6MTcyOTY3ODc1Nn0.FD_SrBqSjquYVL5QuqStgXfhCT0yisShgMSFXyE4a58
@id = 49bcbf46-adad-4483-b6cb-c897834df1df

### create user
POST http://localhost:3000/user
Content-Type: application/json

{
  "name" : "test",
  "email" : "test@test",
  "password" : "test"
}

### login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email" : "test@test",
  "password" : "test"
}

### update user
PUT http://localhost:3000/user/{{id}}
Content-Type: application/json
Authorization: {{authToken}}

{
  "name" : "test updated XXX",
  "password" : "test updated XXX"
}