services:
  postgres:
    image: 'postgres:14.2'
    ports:
      - "3001:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
  # add volumes